config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destory]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 5, maximum: 250 }
    validates :user_id, presence: true
    
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save {self.email = email.downcase}
    validates :username, presence: true, 
               uniqueness: { case_sensitive: false }, 
               length: { minimum: 3, maximum: 25 }
    
    VALID_EMAIL_REGEX= /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i    
    validates :email, presence: true, 
               uniqueness: { case_sensitive: false }, 
               length: { maximum: 105 }, 
               format: {with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?, :get_username

    def current_user
        #Conditional assignment operator - First check if there is a current user,
        #if there is no user, it will find it and set it to the current_user variable!
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def get_username
        current_user[:username]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "Must be logged in to perform that action."
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :show, :destroy, :update]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :destroy, :update]
    
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
    end

    def destroy
        @article.destroy
        flash[:danger] = "Article was successfully deleted."
        redirect_to articles_path
    end

    def update
        if @article.update(article_params)
            flash[:success] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end


    private
    
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You can only edit or delete your own articles."
            redirect_to root_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:show, :index]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def new
        @category = Category.new
    end

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was created successfully"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def edit 
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Category was updated successfully"
            redirect_to categories_path
        else
            render 'edit'
        end
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "Only admins can perform that task."
            redirect_to categories_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:sessions][:email].downcase)
        if user && user.authenticate(params[:sessions][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in."
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Incorrect email or password"
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have successfully logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :show, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update]
    before_action :require_admin, only: [:destory]

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the Blog on Rails, #{@user.username}. Try making an blog article!"
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
    end

    def destroy
        @user.destroy
        flash[:danger] = "All users and their articles have been deleted."
        redirect_to users_path
    end

    def update
        if @user.update(user_params)
            flash[:success] = "#{@user.username}'s profile has been edited successfully.'"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def show
        @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    private
    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "You can only edit your profile."
            redirect_to root_path
        end
    end

    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin users can do that action."
            redirect_to root_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: 'img-circle')
    end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to  article.title, article_path(article) %>
                </div>
                <div class="article-body" align="left">
                    <%= truncate(article.description, length: 100) %>
                    <div class="article-meta-details">
                        <small> Author: <%= article.user.username if article.user %>,
                            Date Created: <%= time_ago_in_words(article.created_at) %> ago,
                            Last Updated: <%= time_ago_in_words(article.updated_at) %> ago
                        </small>
                    </div>
                </div>
                <div align="left">
                <% if article.categories.any? %>
                    <p> Categories: <%= render article.categories %> &nbsp; </p>
                <% end %>
                <% if logged_in? && (current_user == article.user || current_user.admin? ) %>
                    <%= link_to  "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                    <%= link_to  "Delete this article", article_path(article), 
                        method: :delete, 
                        data: { confirm: "Are you sure you want to delete this?" }, 
                        class: "btn btn-xs btn-danger" %>
                <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%-# Error messages -%>
<%= render  "shared/errors", obj: @article %>

<%-# Form for Article -%>
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Enter Title Here" %>
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_area :description, rows: "10", class: "form-control", placeholder: "Enter Description Here" %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :category %>
                </div>
                <div class="col-sm-8">
                    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                        <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
                    <% end %>
                </div>
            </div>
            <div class="center form-group">
                <div class="col-sm-10 col-sm-offset-1">
                    <%= f.submit class: "btn btn-default btn-lg btn-xlarge" %>
                </div>
                <div class="col-sm-10 col-sm-offset-1">
                    [<%= link_to  "Cancel", articles_path %>]
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="center"> Edit Article: </h1>

<%= render  "form" %>

app/views/articles/index.html.erb
<h2 align="center"> Listing all articles </h2>
<div align="center">
    <%= will_paginate %>
</div>
<%= render  "article", obj: @articles %>

<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<%-# Title -%>
<h1 class="center"> Create A New Article: </h1>

<%= render  'form' %>

app/views/articles/show.html.erb
<h2><%= @article.title %> </h2>
<div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
    <ul class="user-listing">
        <div class="row center">
            <li> Created by: </li>
            <div class="col-md-4 col-md-offset-4" align="center">
                <li><%= link_to  gravatar_for(@article.user, size: 25), user_path(@article.user) %></li>
                <li class="article-title"><%= link_to  @article.user.username, user_path(@article.user) %>
                <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
            </div>
        </div>
    </ul>
    <% end %>
    <strong>
    Description:
    </strong>
    <hr>
    <%= simple_format(@article.description) %>
    <% if @article.categories.any? %>
        <p> <%= render @article.categories %> </p>
    <% end %>
    <div class="article-actions" style="padding-top: 10px; border-top: 1px solid #eaeaea">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to  "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
        <%= link_to  "Delete this article", article_path(@article), 
            method: :delete, 
            data: { confirm: "Are you sure you want to delete this?" }, 
            class: "btn btn-xs btn-danger" %>
        <%= link_to  "Back to Articles", articles_path, class: "btn btn-xs btn-success" %>
    <% end %>
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"> <%= link_to category.name, category_path(category) %> &nbsp; </span> 

app/views/categories/_form.html.erb
<%= render  "shared/errors", obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Sports" %>
        </div>
    </div>

    <div class="center form-group">
        <div class="col-sm-10 col-sm-offset-1">
            <%= f.submit class: "btn btn-default btn-lg btn-xlarge" %>
        </div>
        <div class="col-sm-10 col-sm-offset-1">
            [<%= link_to  "Cancel", categories_path %>]
        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1> Edit <%= @category.name %> <h1>

<%= render  "form" %>

app/views/categories/index.html.erb
<h1> Listing all categories </h1>
<%= will_paginate %>
<% @categories.each do |category| %>
    <div class="listing">
        <div class="row">
            <div class="well col-md-4 col-md-offset-4">
                <li class="article-title user-listing">
                    <%= link_to  "#{category.name}", category_path(category) %>
                </li>
                <li style="list-style: none;"> <%= pluralize(category.articles.count, "article") %> </li>
            </div>
        </div>
    </div>
<% end %>
<%= will_paginate %>

app/views/categories/new.html.erb
<h1> Create a new category </h1>

<%= render  "form" %>

app/views/categories/show.html.erb
<h1> Category: <%= @category.name %> </h1>
<% if logged_in? and current_user.admin? %>
    <div class="row">
        <span class="badge"> <%= link_to  "Edit Category Name", edit_category_path(@category) %>
    </div>
<% end %>

<div align="center">
    <%= will_paginate @category_articles %>
</div>

<%= render  "articles/article", obj: @category_articles %>

<div align="center">
    <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            © Daniel Kantor
        </small>
        <nav>
            <ul>
                <li> <%= link_to 'About', about_path %> </li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= "#{name}" %>">
        <a href="#" class="close" data_dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div> 
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to  "Blog on Rails", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Articles", articles_path %> </li>
        <li> <%= link_to "Users", users_path %> </li>
      </ul>

      <% if logged_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= get_username %> <%= "[admin]" if current_user.admin? %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to  "New Article", new_article_path %></li>
            <li><%= link_to  "Edit your profile", edit_user_path(current_user) %></li>
            <li><%= link_to  "View your profile", user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to  "Create new Article", new_article_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to  "About us", about_path %></li>
          </ul>
        </li>
      </ul>
      <% end %>

      <ul class="nav navbar-nav navbar-left">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to  "All Categories", categories_path %></li>
            <% Category.all.each do |category| %>
            <li><%= link_to  "#{category.name}", category_path(category) %></li>
            <% end %>
            <% if logged_in? and current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to  "Create new Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-right">
        <% if logged_in? %>
          <%= link_to  "Logout", logout_path, method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to  "Login", login_path, class: "btn btn-default" %>
        <% end %>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog on Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/navigation" %>
    <%= render  "layouts/messages" %>
    <div class="center container" >
      <%= yield %>
    </div>
    <div class="center container" >
      <%= render  "layouts/footer" %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is the alpha about page </h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to Blog on Rails!</h1>
  <p>A basic blog application made with Ruby on Rails. What can it do?</p>
  <% if !logged_in? %>
    <p><%= link_to  "Sign up here!", signup_path, class: 'btn btn-default btn-lg btn-xlarge' %></p>
  <% else %>
    <p><%= link_to  "See all articles!", articles_path, class: 'btn btn-default btn-lg btn-xlarge' %></p>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>. Please fix them to continue.
                    </h2>
                </div>
                <div class="panel-body red-color">
                    <ul>
                        <% obj.errors.full_messages.each do |msg| %>
                            <li> <%= msg %> </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%-# Error messages -%>
<%= render  "shared/errors", obj: @user %>

<%-# Form for User -%>
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :username %>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :username, class: "form-control", placeholder: "JohnDoe" %>
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email %>
                </div>
                <div class="col-sm-8">
                    <%= f.email_field :email, class: "form-control", placeholder: "JohnDoe@gmail.com" %>
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :password %>
                </div>
                <div class="col-sm-8">
                    <%= f.password_field :password, class: "form-control", placeholder: "JohnDoe123!" %>
                </div>
            </div>

            <div class="center form-group">
                <div class="col-sm-10 col-sm-offset-1">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-default btn-lg btn-xlarge") %>
                </div>
                <div class="col-sm-10 col-sm-offset-1">
                    [<%= link_to  "Cancel", articles_path %>]
                </div>
                
            </div>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h1> Edit your account </h1>

<%= render  "form" %>

app/views/users/index.html.erb
<h1> All users on Blog on Rails </h1>

<div align="center">
    <%= will_paginate %>
    <% @users.each do |user| %>
    <ul class="user-listing">
        <div class="row">
            <div class="well col-md-4 col-md-offset-4" align="center">
                <li><%= link_to  gravatar_for(user, size: 50), user_path(user) %></li>
                <li class="article-title"><%= link_to  user.username, user_path(user) %>
                <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
                <% if logged_in? and current_user.admin? %>
                    <li><%= link_to  "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete this user?" } %></li>
                <% end %>
            </div>
        </div>
    </ul>
    <% end %>
</div>

<div align="center">
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h2> Sign up to use Blog on Rails </h2>

<%= render  "form" %>

app/views/users/show.html.erb
<h1> <%= @user.username %>'s profile </h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user, size: 150 %>
    </div>
</div>
<h4> <%= @user.username %>'s aricles </h4>
<div class="center">
    <%= will_paginate @user_articles %>
</div>
<%= render  "articles/article", obj: @user_articles %>
<div class="center">
    <%= will_paginate @user_articles %>
</div>